#!/bin/bash
if [ "$#" -gt 0 ] && [ "$@" == "upd" ]; then
	curl -o tarkov 'https://raw.githubusercontent.com/bgkillas/tarkov/main/tarkov'
	if [ "$(stat -c %U ${BASH_SOURCE[0]})" == "$USER" ];then
	diff tarkov "${BASH_SOURCE[0]}"
	cat tarkov > "${BASH_SOURCE[0]}"
	rm tarkov
	else
	echo "you do not own ${BASH_SOURCE[0]}"
	fi
	exit
fi
chmod +x "${BASH_SOURCE[0]}"
mkdir -p "$HOME"/.config/tarkov/cfg &>/dev/null
set -e
cd "$HOME"
CFG="$HOME/.config/tarkov"
if [ ! -d "$HOME/.local/share/Steam/steamapps/common/Proton BattlEye Runtime" ]; then
	echo "$HOME/.local/share/Steam/steamapps/common/Proton BattlEye Runtime does not exist make sure 'Proton Battleye Runtime' tool is installed"
	exit
fi
if [ -f "$HOME/.config/tarkov/proton" ] && [ "$(cat "$HOME"/.config/tarkov/proton | wc -l)" -eq 1 ]; then
	PROTON="$(cat "$HOME"/.config/tarkov/proton)"
elif [ -d "$HOME/.local/share/Steam/steamapps/common/Proton 7.0" ]; then
	PROTON="$HOME/.local/share/Steam/steamapps/common/Proton 7.0"
else
	echo "$HOME/.local/share/Steam/steamapps/common/Proton 7.0 does not exist specify proton directorys full path in the file $HOME/.config/tarkov/proton"
	exit
fi
if [ -d "$PROTON/*/bin" ]; then
	echo "$PROTON/*/bin does not exist run a game with the proton install and try again"
	exit
fi
if [ ! -d "$CFG/pfx" ] || [ ! -d "$CFG/bsg" ]; then
	curl 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' -o winetricks
	curl -L 'https://github.com/dscharrer/innoextract/releases/download/1.9/innoextract-1.9-linux.tar.xz' -o inno.tar.xz
	curl -L 'https://prod.escapefromtarkov.com/launcher/download' -o bsglauncher.exe
	set +e
	rm -rf "$HOME"/.config/tarkov/{bsg,pfx}
	set -e
	tar -xf inno.tar.xz
	cd innoextract-1.9-linux
	./innoextract -s ../bsglauncher.exe
	mv app "$HOME"/.config/tarkov/bsg
	cd ..
	rm -rf tmp bsglauncher.exe inno.tar.xz innoextract-1.9-linux
	WINEDEBUG=-all \
		PATH="$(eval echo "$PROTON"/*/bin):$PATH" \
		WINE="$(eval echo "$PROTON"/*/bin/wine64)" \
		WINEPREFIX="$CFG/pfx" \
		sh winetricks -q -f dotnet48
	rm -rf winetricks
	ln -sf "$HOME"/.config/tarkov/cfg "$CFG/pfx/drive_c/users/steamuser/AppData/Roaming/Battlestate Games"
	ln -sf "$CFG/pfx/drive_c/windows/syswow64/websocket.dll" "$CFG/pfx/drive_c/windows/system32"
	ln -sf "$CFG/pfx/drive_c/Battlestate Games/EFT" "$CFG/eft"
	WINEPREFIX="$CFG/pfx" \
		"$PROTON"/*/bin/wine64 winecfg -v win10
	rm -rf "$CFG/pfx/drive_c/windows/Fonts"
	ln -sf "$PROTON"/*/share/fonts "$CFG/pfx/drive_c/windows/Fonts"
	ln -sf "$PROTON"/*/lib64/wine/dxvk/d3d11.dll "$CFG/pfx/drive_c/windows/system32/d3d11.dll"
	ln -sf "$PROTON"/*/lib64/wine/dxvk/dxgi.dll "$CFG/pfx/drive_c/windows/system32/dxgi.dll"
fi
sleep 3
cd "$HOME/.config/tarkov/bsg"
if [ -f /home/.config/tarkov/prerun ]; then
	PROTON_BATTLEYE_RUNTIME="$HOME/.local/share/Steam/steamapps/common/Proton BattlEye Runtime" \
		WINEDLLOVERRIDES='d3d11=n' \
		WINEFSYNC='1' \
		WINEDEBUG='-all' \
		WINEPREFIX="$CFG/pfx" \
		$(cat /home/.config/tarkov/prerun) \
		"$PROTON"/*/bin/wine64 \
		"$HOME/.config/tarkov/bsg/BsgLauncher.exe"
else
	PROTON_BATTLEYE_RUNTIME="$HOME/.local/share/Steam/steamapps/common/Proton BattlEye Runtime" \
		WINEDLLOVERRIDES='d3d11=n' \
		WINEFSYNC='1' \
		WINEDEBUG='-all' \
		WINEPREFIX="$CFG/pfx" \
		"$PROTON"/*/bin/wine64 \
		"$HOME/.config/tarkov/bsg/BsgLauncher.exe"
fi
